export default data = {
    "_id": 51852129,
    "list":
        [{
            "list/name_of_post": "Sammy Post",
            "list/target_population": 50,
            "list/other_factor_specify": "0",
            "list/children_vaccinated/years3_5": 5,
            "list/children_vaccinated/years6_14": 5,
            "list/children_vaccinated/months9_11": 5,
            "list/children_vaccinated/months12_24": 10,
            "list/post_staffing/number_mobilizers": 2,
            "list/post_staffing/number_health_workers": 4,
            "list/mr_vaccine_usage/no_vaccine_vials_issued": 20,
            "list/mr_vaccine_usage/no_diluent_ampules_issued": 2,
            "list/mr_vaccine_usage/no_vials_discarded_other_factors": "0",
            "list/mr_vaccine_usage/no_vaccine_vials_returned_unopened": 2,
            "list/mr_vaccine_usage/no_vials_discarded_due_partial_use": 2,
            "list/mr_vaccine_usage/no_diluent_ampules_returned_unopened": 2,
            "list/mr_vaccine_usage/no_vials_discarded_due_contamination": 2,
            "list/mr_vaccine_usage/no_vials_discarded_due_vvm_color_change": 2
        }, {
            "list/name_of_post": "Kiss Post",
            "list/target_population": 100,
            "list/other_factor_specify": "0",
            "list/children_vaccinated/years3_5": 25,
            "list/children_vaccinated/years6_14": 25,
            "list/children_vaccinated/months9_11": 25,
            "list/children_vaccinated/months12_24": 35,
            "list/post_staffing/number_mobilizers": 2,
            "list/post_staffing/number_health_workers": 3,
            "list/mr_vaccine_usage/no_vaccine_vials_issued": 10,
            "list/mr_vaccine_usage/no_diluent_ampules_issued": 2,
            "list/mr_vaccine_usage/no_vials_discarded_other_factors": 5,
            "list/mr_vaccine_usage/no_vaccine_vials_returned_unopened": 10,
            "list/mr_vaccine_usage/no_vials_discarded_due_partial_use": 5,
            "list/mr_vaccine_usage/no_diluent_ampules_returned_unopened": 2,
            "list/mr_vaccine_usage/no_vials_discarded_due_contamination": 5,
            "list/mr_vaccine_usage/no_vials_discarded_due_vvm_color_change": 5
        }],
    "_tags": [],
    "_uuid": "1721ba1d-4f38-407a-bb59-89709240727f",
    "today": "2019-09-26",
    "_notes": [],
    "region": "GREATER_KAMPALA",
    "_edited": false,
    "_status": "submitted_via_web",
    "endtime": "2019-09-26T12:14:11.799+03:00",
    "_version": "201909101245",
    "deviceid": "359116082940660",
    "num_post": 2,
    "_duration": 166,
    "_xform_id": 411165,
    "districts": "KAMPALA",
    "starttime": "2019-09-26T12:11:25.131+03:00",
    "subcounty": "nakawa_division",
    "list_count": "2",
    "_attachments": [],
    "_geolocation": [null, null],
    "_media_count": 0,
    "_total_media": 0,
    "formhub/uuid": "d77bf394ad0043ee9c02ae719069e153",
    "_submitted_by": null,
    "day_of_results": "day_one",
    "date_of_results": "2019-09-26",
    "meta/instanceID": "uuid:1721ba1d-4f38-407a-bb59-89709240727f",
    "_submission_time": "2019-09-26T09:14:32",
    "_xform_id_string": "mr_subcounty_level_total_checklist",
    "_bamboo_dataset_id": "",
    "_media_all_received": true,
    "mobile_number_supervisor": "0705415338",
    "name_district_supervisor": "Samuel"
}